feat: Migrate to yarn workspaces
DiceDB/alloy pull request #79
Opened 2024-10-30 12:09 UTC by AjayPoshak

2024-10-30 12:53 UTC, lucifercr07 requested changes
We'd need to update the README also accordingly.

2024-10-30 16:10 UTC, AjayPoshak commented
> We'd need to update the README also accordingly.

good point, done

2024-10-31 19:58 UTC, lucifercr07 approved these changes

2024-11-02 13:08 UTC, KaviiSuri approved these changes

2024-11-02 15:04 UTC, merged